# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiKeys',
            fields=[
                ('id', models.CharField(max_length=200)),
                ('key', models.UUIDField(default=b'9595b41e4fa84b789c2374131ddde74e', editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ButtonTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.IntegerField(choices=[(0, b'Skranke'), (1, b'Telefon'), (2, b'Random')], default=0)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='bujumbura.apiKeys')),
            ],
        ),
    ]
