# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujumbura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='key',
            field=models.UUIDField(default=b'e4adb1396276443aadeb8c45b6ba96c6', primary_key=True, serialize=False),
        ),
    ]
