# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujumbura', '0002_auto_20161108_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='key',
            field=models.TextField(default=b'585c3cfc6d784382b548d00f2b17f357', primary_key=True, serialize=False),
        ),
    ]
